import Head from "next/head";
import { useRouter } from "next/router";
import { useMoralis } from "react-moralis";
import MainSection from "../components/MainSection";

export default function Home() {
  const { user, account, isAuthenticated } = useMoralis();
  const router = useRouter();

  const handleRedirect = async () => {
    const d = await user;
    if (d.attributes.discordId) {
      router.push(`/${d.attributes.discordId}`);
    } else return alert("You need to enter your discordId to proceed");
  };

  return (
    <div className="w-full flex flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex flex-col items-center justify-center">
        <MainSection />
        <div
          className={`bg-discord rounded-md p-4 mt-5 cursor-pointer ${
            isAuthenticated ? "visible" : "hidden"
          } `}
          onClick={handleRedirect}
        >
          GET NFT records
        </div>
      </div>
    </div>
  );
}
