import Head from "next/head";
import MainSection from "../components/MainSection";
import NFT from "../components/NFT";

export default function Home() {
  return (
    <div className="w-full flex flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex flex-col items-center justify-center">
        <MainSection />
        <NFT />
      </div>
    </div>
  );
}
